### ISSUE TITLE
bit operation details

### ISSUE THREAD

**Issue by mariogeiger** [adafruit/Adafruit-MAX31855-library#10]
In the file Adafruit-MAX31855-library/Adafruit_MAX31855.cpp at line 98  :
v = 0xFFFFC000 | ((v >> 18) & 0x00003FFFF);

I think that 0x00003FFFF should be 0x00003FFF
But I also think that it changes nothing and ((v >> 18) & 0x00003FFFF); can be replaced by (v >> 18)

**Comment by caternuson** [comment]
Should be fixed with #36 
https://github.com/adafruit/Adafruit-MAX31855-library/releases/tag/1.1.1
