### ISSUE TITLE
Serial Display Sample Code (serialthermocouple) does not compile 

### ISSUE THREAD

**Issue by thescreensavers** [adafruit/Adafruit-MAX31855-library#11]
Arduino: 1.6.6 (Windows 10), Board: "Arduino/Genuino Uno"

Build options changed, rebuilding all
serialthermocouple:28: error: redefinition of 'Adafruit_MAX31855 thermocouple'

 Adafruit_MAX31855 thermocouple(CLK, CS, DO);

                               ^

serialthermocouple:28: error: 'Adafruit_MAX31855 thermocouple' previously declared here

 Adafruit_MAX31855 thermocouple(CLK, CS, DO);

                   ^

D:\Users\Danny\Documents\Arduino\libraries\Adafruit-MAX31855-library-master\examples\serialthermocouple\serialthermocouple.ino: In function 'void setup()':

serialthermocouple:35: error: redefinition of 'void setup()'

 void setup() {

      ^

serialthermocouple:35: error: 'void setup()' previously defined here

 void setup() {

      ^

D:\Users\Danny\Documents\Arduino\libraries\Adafruit-MAX31855-library-master\examples\serialthermocouple\serialthermocouple.ino: In function 'void loop()':

serialthermocouple:43: error: redefinition of 'void loop()'

 void loop() {

      ^

serialthermocouple:43: error: 'void loop()' previously defined here

 void loop() {

      ^

exit status 1
redefinition of 'Adafruit_MAX31855 thermocouple'

  This report would have more information with
  "Show verbose output during compilation"
  enabled in File > Preferences.

**Comment by thescreensavers** [comment]
I have redownloaded the file but simply opening the example from the file menu causes this issue, but LCD Sample code works fine.

**Comment by ladyada** [comment]
hmmm you got something kinda wacky going on. please remove any and all copies of the library code, then install the latest version by downloading the zip & manually installing & try again?
