### ISSUE TITLE
SPI, the "new" way

### ISSUE THREAD

**Issue by stylesuxx** [adafruit/Adafruit-MAX31855-library#15]
After reading the issue template I am not sure if contributions are welcome, but I refactored the SPI related code to work the "new" way, with the SPI library, using [SPISettings](https://www.arduino.cc/en/Reference/SPISettings), [SPIbeginTransaction](https://www.arduino.cc/en/Reference/SPIbeginTransaction) and [SPIendTransaction](https://www.arduino.cc/en/Reference/SPIendTransaction).

Let me know if this is something you are willing to merge and I will prepare a PR.

**Comment by ladyada** [comment]
i did this ! :)
