### ISSUE TITLE
SPI.begin (SERCOM::disableSPI) hangs on SAMD21 M0 in class instantiate

### ISSUE THREAD

**Issue by PaulZC** [adafruit/Adafruit-MAX31855-library#16]
Hi Gang,
This library needs an update to keep it compatible with the M0. The SPI.begin in the class instantiate - before setup() - is causing problems.
Please see [https://github.com/arduino/ArduinoCore-samd/issues/166](url) for further details.
(That issue is linked to the Sparkfun MAX31855 library - but the same is true for this one.)
Possibly linked to issue #15?
Cheers, Paul

**Comment by ladyada** [comment]
fixed now !

**Comment by PaulZC** [comment]
Nice one. Thank you!
