### ISSUE TITLE
Wrong SPI mode ?

### ISSUE THREAD

**Issue by fededim** [adafruit/Adafruit-MAX31855-library#19]
In file [Adafruit_MAX31855.cpp (row 145)](https://github.com/adafruit/Adafruit-MAX31855-library/blob/master/Adafruit_MAX31855.cpp#L145) you are using SPI mode 0, but on [MAX31855 faq](https://www.maximintegrated.com/en/support/faqs/max31855-faq.html) it states that the chip only supports Mode 1.

**Which SPI mode does the MAX31855 use?
The MAX31855 implements a read-only Mode 1 SPI interface.**

Are you sure that spi mode 0 is correct ? Using a chinese compatible board I have issues in both modes (probably I have a defective chip), but I just wanted to point it out.

**Comment by caternuson** [comment]
The datasheet talks about the value changing *after* the falling edge, so sounds like you read it on the rising edge, which would be CPHA=0 / Mode0.
![screenshot](https://user-images.githubusercontent.com/8755041/72285618-5906c980-35f8-11ea-8acc-6d237bedee1c.png)

**Comment by caternuson** [comment]
Closing this for now. Can't verify and everything seems to currently be working OK with current mode. If someone can come up with a test case to verify this, we can reopen.
