### ISSUE TITLE
Needed 3.3v-5v level shifter.

### ISSUE THREAD

**Issue by carlerickrowan** [adafruit/Adafruit-MAX31855-library#20]
I have a MAX31855 breakout board then I tried the Adafruit library but it didn't work right. 3.3 is the Vin and SPI pins are interfaced to 5V arduino. When I put level shifter, the library works smooth. 

This library works very well. Just extra note on the level-shifter.

**Comment by caternuson** [comment]
For a 5V board, use 5V for Vin as well.
https://learn.adafruit.com/thermocouple/arduino-code#adding-a-display-3-15
