### ISSUE TITLE
Max31855 not working on wemos/esp8266

### ISSUE THREAD

**Issue by paai** [adafruit/Adafruit-MAX31855-library#22]
I am using three or four Adafruit MAX31855 on UNO and MEGA boards and they work as advertised. However, when I try to use them on a esp8266-based WEMOS D1 R2 the program crashes in a lot of interesting ways when I try to read the temperature.

Is it at all possible to use this combination?

/ ------------------- Thermocouple board -------------------

#include "Adafruit_MAX31855.h"
int thermoCLK = 4;   
int thermoCS  = 5;   
int thermoDO  = 6;  
Adafruit_MAX31855 thermocouple(thermoCLK, thermoCS, thermoDO);
...
void loop() {
double temperatuur;
temperatuur=thermocouple.readCelsius();
}

**Comment by vikingasia** [comment]
I only know UNO board; so I’d have to do a lot of twiddling???

i just finished soldering 11 displays

Roofers are here, and I have several other irons in the fire, at this instant, give me a few hours....

**Comment by fakecrusader** [comment]
I had the same issue I think - you don't give the "crash" details but it was a cause 4 reset in my case.
I had the same pin assignments, which are OK on Arduino but seem to conflict on Wemos D1, so I changed them to:

#define DO   14
#define CS   12
#define CLK  13
 // initialize the Thermocouple
Adafruit_MAX31855 thermocouple(CLK, CS, DO);

Crashes stopped, but I haven't tested the reads yet.

**Comment by caternuson** [comment]
Tested on a Feather ESP8266 using
```
#define MAXDO   14
#define MAXCS   12
#define MAXCLK  13
```
and it ran OK.

This may be hardware related. Please post in the forums:
https://forums.adafruit.com/
