### ISSUE TITLE
Would you mind how can i setoffset for Max31855 

### ISSUE THREAD

**Issue by wiriyo** [adafruit/Adafruit-MAX31855-library#23]
How can i set offset temperature on Max31855
so i also use Max6675K 
that easy for setoffset on its
by
 
ts.setOffset(0);

but this is not can use for Max31855 
้how can i setoffset for Max31855?
Thanks...

**Comment by caternuson** [comment]
What does setOffset() do? If you can define the functionality more clearly, then your issue acts as a feature request. To add the functionality, someone would then need to make a pull request.

**Comment by ladyada** [comment]
set offsets in user code please
