### ISSUE TITLE
Incorrect calculation for negative values - too many hex digits.

### ISSUE THREAD

**Issue by hydra** [adafruit/Adafruit-MAX31855-library#29]
Spotted this mistake today:

https://github.com/adafruit/Adafruit-MAX31855-library/blob/master/Adafruit_MAX31855.cpp#L103

```
v = 0xFFFFC000 | ((v >> 18) & 0x00003FFFF);
```
should likely be:

```
v = 0xFFFFC000 | ((v >> 18) & 0x00003FFF);
```

**Comment by per1234** [comment]
Duplicate of https://github.com/adafruit/Adafruit-MAX31855-library/issues/21

**Comment by hydra** [comment]
yes, closing.
