### ISSUE TITLE
SPI transaction not working on M0

### ISSUE THREAD

**Issue by caternuson** [adafruit/Adafruit-MAX31855-library#33]
Re these threads:
https://forums.adafruit.com/viewtopic.php?f=57&t=160689
https://forums.adafruit.com/viewtopic.php?f=57&t=137134

Recreated.

Appears to be related to toggling of the clock line from `SPI.beginTransaction()` which causes the MAX31855 to start clocking out data. Shows up in data as an off-by-one.
**Feather M0:**
![image](https://user-images.githubusercontent.com/8755041/72289996-231a1300-3601-11ea-89a4-af08ff128fe0.png)

Not present on an **UNO**:
![image](https://user-images.githubusercontent.com/8755041/72289973-1695ba80-3601-11ea-8951-e753a51dc233.png)

**Comment by ladyada** [comment]
we could move this library to use BusIO - will solve any side-effects?

**Comment by caternuson** [comment]
Moving  `SPI.beginTransaction()` before the CS assert seems to work as well. But might as well move to BusIO? watcha think?

**Comment by caternuson** [comment]
nvm. wasn't too hard to swap to busio, totes the way to go. pr'd.

**Comment by ladyada** [comment]
i think lets just move it - will fix various issues and make code a lot more future proof! also good practice for ya :)
