### ISSUE TITLE
Fix begin() and add to examples?

### ISSUE THREAD

**Issue by caternuson** [adafruit/Adafruit-MAX31855-library#38]
Probably should have `begin()` actually return the bool result:
https://github.com/adafruit/Adafruit-MAX31855-library/blob/69347a4c8172df2f81cfbab573d80326045aa817/Adafruit_MAX31855.cpp#L80

Also noting that the examples are not calling `begin()`.

Also also - since `initialized` is private, would it be useful to have a getter for it?

**Comment by ladyada** [comment]
@caternuson this library could use some luv - maybe also convert it to busio - wanna do that in next few weeks?

**Comment by caternuson** [comment]
It looks like maybe I already did the busio conversion? Also doxy and actions and some other housekeeping.

This `begin()` thing is maybe just a little detail that was overlooked?

**Comment by ladyada** [comment]
oh duh - yeah go for it then. lol i was thinking ot max31865

**Comment by caternuson** [comment]
Hopefully taken care of with #39
