### ISSUE TITLE
bad data ?

### ISSUE THREAD

**Issue by tablatronix** [adafruit/Adafruit-MAX31855-library#40]
Has anyone ever seen this before?
This is an ebay module, I have to see if I can reproduce on my adafruit module, maybe its a bad chip..

If my TC is less than CJ, I get this..
This is typically only during this condition, this is at around 28C 
If TC is warmer than cj it stops..

Could be noise.., but its so consistantly reproducible which is odd..

debugs are uncommented from lib, error is mine, should be 24C getting -x.xx

```PHP
[TC RAW]1100011000001101101100000
0x18C1B60
[TC RAW]11111111110110000001101101110000
0xFFD81B70
[ERROR] TC OUT OF RANGE, skipping -2.50
[TC RAW]1100100000001101101100000
0x1901B60
[TC RAW]1100011000001101101100000
0x18C1B60
[TC RAW]1100100000001101101100000
0x1901B60
[TC RAW]1100100000001101101100000
0x1901B60
[TC RAW]1100100000001101101100000
0x1901B60
[TC RAW]1100100000001101101100000
0x1901B60
[TC RAW]1100010000001101101100000
0x1881B60
[TC RAW]1100100000001101101100000
0x1901B60
[TC RAW]11111111011110000001101101100000
0xFF781B60
[ERROR] TC OUT OF RANGE, skipping -8.50
[TC RAW]1100100000001101101100000
0x1901B60
[TC RAW]1100100000001101101100000
0x1901B60
[TC RAW]1100100000001101101100000
```

**Comment by caternuson** [comment]
Closing. Can reopen if this check was done with an Adafruit module and shows the same behavior:

> I have to see if I can reproduce on my adafruit module, maybe its a bad chip..
