### ISSUE TITLE
This library should allow the user to specify which SPI Device to use, like most of your libraries

### ISSUE THREAD

**Issue by KurtE** [adafruit/Adafruit-MAX31855-library#43]
Up on the PJRC Forum another member created a thread: 
https://forum.pjrc.com/threads/66607-difference-between-teensy3-6-and-Teensy4-1-SPI-configuration

Where he is trying to use the pins associated with SPI1 with this device.  My quick look through I did not see any locations in this library that allows the user to specify SPI1.  In many of your libraries you either allow it on the constructor or on a begin method.

I suggested that maybe the user should try something like:
either add or modify a constructor in the header file, something like:
```
class Adafruit_MAX31855 {
public:
  Adafruit_MAX31855(int8_t _sclk, int8_t _cs, int8_t _miso);
  Adafruit_MAX31855(int8_t _cs, SPIClass *theSPI = &SPI);
```
Don't know if this would need to be conditional for some processors...
But assuming this would work, I  would think the implementation would simply be:
```
Adafruit_MAX31855::Adafruit_MAX31855(int8_t _cs, SPIClass *theSPI) : spi_dev(_cs, 1000000, SPI_BITORDER_MSBFIRST, SPI_MODE0, theSPI) {}
```

Note: I typed on fly and did not try to build nor do I have devices to try it on.  Also not sure if maybe the other constructor should also have the optional parameter as well...

**Comment by ladyada** [comment]
sounds good! please submit a PR and we'll test/merge it :)
